##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.nginx:1.17.3 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo/*
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV INFOMETIS_CONTAINERENTRYPOINT "/infometis/bin/nginx/base/entrypoint"
COPY ./infometis///etc/nginx/nginx.conf /etc/nginx/nginx.conf
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="nginx" \
    CONTECO_NAME="base" \
    CONTECO_TAG="1.17.3" \
    CONTECO_BASE="external.nginx:1.17.3" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="nginx" \
      io.vcweb.name="base" \
      io.vcweb.tag="1.17.3" \
      io.vcweb.base="external.nginx:1.17.3" \
      io.vcweb.build="image-base" \
      io.vcweb.label="Conteco Nginx base" \
      io.vcweb.description="The Nginx base image." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.nginx.base --help" 
##### END image.base/Dockerfile/env-labels-footer #####
