#!/usr/bin/env bash

export CONTECO_LABEL="Conteco Nginx base"
export CONTECO_DESCRIPTION="The Nginx base image."

export CONTECO_TYPE="nginx"
export CONTECO_NAME="base"
export CONTECO_TAG="1.17.3"

export CONTECO_BASE="external.nginx:1.17.3"
export CONTECO_BUILD="image-base"
