#!/usr/bin/env bash

export CONTECO_LABEL="nginx.base - ContEco"
export CONTECO_DESCRIPTION="See `conteco.docs.overview` for more information on the ContEco ecosystem."

export CONTECO_TYPE="nginx"
export CONTECO_NAME="base"
export CONTECO_TAG="1.17.3"

export CONTECO_BASE="external.nginx:1.17.3"
export CONTECO_BUILD="image-base"
