---
version: '3'
services:

# START SERVICE nginx.base
  nginx:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.nginx.base:1.17.3
    environment: []
    command: []
    volumes: []
    ports: [81:80]
    networks: [${CONTECO_NETWORKGLOBAL}_overlay, ${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [${CONTECO_DC_NGINX_DEPLOY_LABELS}]
# END SERVICE nginx.base

volumes: {}
networks: {${CONTECO_NETWORKGLOBAL}_overlay: { external: true }, ${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
