---
version: '3'
services:

# START SERVICE nginx.base
  nginx:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.nginx.base:1.17.3
    environment: []
    command: []
    volumes: []
    ports: [81:80]
    networks: [${CONTECO_NETWORKGLOBAL}_overlay, ${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${CONTECO_DC_NGINX_DEPLOY_PLACEMENT_CONSTRAINTS}]
      ${CONTECO_DC_BASH_DEPLOY_EXTENSIONS}
    ${CONTECO_DC_BASH_SERVICE_EXTENSIONS}
# END SERVICE nginx.base

networks: {${CONTECO_NETWORKGLOBAL}_overlay: { external: true }, ${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {}
${CONTECO_DC_BASH_GLOBAL_EXTENSIONS}
