---
version: '3'
services:

# START SERVICE nginx.base
  nginx:
    image: ${CONTECO_REGISTRY}nginx:1.19.3 
    environment: []
    command: []
    volumes: []
    ports: [81:80]
    networks: [${CONTECO_NETWORKGLOBAL}_overlay, ${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${CONTECO_DC_NGINX_COMPOSE_EXTENSIONS}
# END SERVICE nginx.base

networks: {${CONTECO_NETWORKGLOBAL}_overlay: { external: true }, ${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
