---
version: '3'
services:

# START SERVICE nginx.base
  nginx:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.nginx.base:1.17.3
    environment: []
    command: []
    volumes: [${CONTECO_DC_NGINX_VOLUMES}]
    ports: [81:80]
    networks: [${CONTECO_ECOSYSTEM_RUNTIME}_overlay, ${CONTECO_TYPE}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_NGINX_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [${CONTECO_DC_NGINX_DEPLOY_LABELS}]
# END SERVICE nginx.base

volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
networks: {${CONTECO_ECOSYSTEM_RUNTIME}_overlay: { external: true }, ${CONTECO_TYPE}_overlay: { external: true }}
