---
version: '3'
services:

# START SERVICE nginx.base
  nginx:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.nginx.base:1.17.3
    environment: [${CONTECO_DC_NGINX_ENVIRONMENT}] 
    command: [${CONTECO_DC_NGINX_COMMAND}]
    volumes: [${CONTECO_DC_NGINX_VOLUMES}]
    ports: [${CONTECO_DC_NGINX_PORTS}]
    networks: [${CONTECO_DC_NGINX_NETWORKS}]
    deploy: {${CONTECO_DC_NGINX_DEPLOY}}
# END SERVICE nginx.base

networks:
  ${CONTECO_DC_NGINX_NETWORKS}:
    external: true
